#!/bin/sh
# a4norm: runs the build of the a4norm binary for this machine, from bin/.
# They are built from github.com/georg-malahov/a4norm (a4norm-rs/) and give
# the same bytes on every platform.
self=$0
while [ -L "$self" ]; do
  t=$(readlink "$self")
  case $t in /*) self=$t ;; *) self=$(dirname "$self")/$t ;; esac
done
case "$(uname -s)-$(uname -m)" in
  Darwin-arm64) b=darwin-arm64 ;;
  Darwin-x86_64) b=darwin-x86_64 ;;
  Linux-x86_64 | Linux-amd64) b=linux-x86_64 ;;
  Linux-aarch64 | Linux-arm64) b=linux-aarch64 ;;
  *) b= ;;
esac
bin=$(dirname "$self")/bin/a4norm-$b
[ -n "$b" ] && [ -x "$bin" ] && exec "$bin" "$@"
echo "a4norm: no build for $(uname -s) $(uname -m) here. Build one with" >&2
echo "  cargo install --git https://github.com/georg-malahov/a4norm a4norm-rs --features par" >&2
echo "or run the image: docker run --rm -v \"\$PWD:/work\" ghcr.io/georg-malahov/a4norm FILE" >&2
exit 1
